version: "3.7"

volumes:
  mysql_node:


networks:
  node_api_network:


services:
  api_service:
    build: .
    image: node_api
    networks:
      - node_api_network
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql_service
      MYSQL_USER: root
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: root
      MYSQL_DB: api
    depends_on:
      - mysql_service

  mysql_service:
    image: mysql
    container_name: database
    volumes:
      - mysql_node:/var/lib/mysql
      - ./src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - node_api_network
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
